alias mv='mv -n'
alias lsa='ls -a'
alias syazi='sudo .local/bin/yazi'
alias debug-gtk='env GTK_DEBUG=interactive'
alias bios='systemctl reboot --firmware-setup'

alias dnfs='dnf search'
alias dnfi='sudo dnf install'
alias dnfu='sudo dnf upgrade'
alias dnfr='sudo dnf remove'
alias dnfl='dnf list'
alias dnfli='dnf list installed'
alias dnfui='dnf repoquery --userinstalled'

alias fpi='flatpak install'
alias fpu='flatpak update'