# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
#exec-once = ~/.local/bin/kanata --cfg ~/.config/kanata.kbd
exec-once = nm-applet & $bar # & brightnessctl set 255 & espanso start
exec-once = wl-paste --watch cliphist store
exec = ~/.config/scripts/lidswitch.sh
