# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
#exec-once = ~/.local/bin/kanata --cfg ~/.config/kanata.kbd
exec-once = swayosd-server & nm-applet & $bar & udiskie -t # & brightnessctl set 255 & espanso start
exec-once = wl-paste --watch cliphist store
exec = ~/.config/scripts/lidswitch.sh
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] $editor
